---
production:
  :concurrency: 20
development:
  :concurrency: 1
test:
  :concurrency: 1

:queues:
  - default
  
:schedule:
  RefreshSuggestionsWorker:
    cron: "0 0 * * *" # Every day at midnight
